-- ================================================================
-- ADMA — Seed : Villes et Quartiers de Ngaoundéré (données officielles)
-- Région : Adamaoua | Département : Vina
-- Source : Données JSON
-- ================================================================

INSERT INTO cities (id, name, region) VALUES
  (1, 'Ngaoundéré 1er', 'Adamaoua'),
  (2, 'Ngaoundéré 2e', 'Adamaoua'),
  (3, 'Ngaoundéré 3e', 'Adamaoua');

-- ── Ngaoundéré 1er ──────────────────────────────────────────────
INSERT INTO neighborhoods (city_id, name) VALUES
  (1, 'Quartier Administratif'),
  (1, 'Mbideng'),
  (1, 'Camp Fonctionnaire'),
  (1, 'Ndelbé'),
  (1, 'Bali'),
  (1, 'Boumdjéré'),
  (1, 'Mission Catholique'),
  (1, 'Gambara'),
  (1, 'Mayo-Djarandi'),
  (1, 'Burkina'),
  (1, 'Bamyanga'),
  (1, 'Bamyanga Hamadjangui'),
  (1, 'Bamyanga Pana'),
  (1, 'Marza'),
  (1, 'Ngaoundang'),
  (1, 'Sioutéré'),
  (1, 'Laïga'),
  (1, 'Wakwa'),
  (1, 'Quartier Lissey'),
  (1, 'Marma'),
  (1, 'Haut Plateau'),
  (1, 'Kantalang'),
  (1, 'Béka-Hosséré'),
  (1, 'Mbibackla-Hosséré'),
  (1, 'Vina-Pont'),
  (1, 'Falfa'),
  (1, 'Bondjong'),
  (1, 'Onaref'),
  (1, 'Norvégien'),
  (1, 'Socaret');

-- ── Ngaoundéré 2e ───────────────────────────────────────────────
INSERT INTO neighborhoods (city_id, name) VALUES
  (2, 'Baladji'),
  (2, 'Cifan'),
  (2, 'Gare Marchandise'),
  (2, 'Haoussa'),
  (2, 'Joli Soir'),
  (2, 'Gada Mabanga'),
  (2, 'Gada Mabanga-Djalingo'),
  (2, 'Kormari'),
  (2, 'Madagascar'),
  (2, 'Maloumri-Damari'),
  (2, 'Mbibar'),
  (2, 'Nord-Cifan'),
  (2, 'Sabongari'),
  (2, 'Tongo'),
  (2, 'Tongo Falingo'),
  (2, 'Tongo Galdima'),
  (2, 'Tongo Pastoral'),
  (2, 'Tongo Seret'),
  (2, 'Troua Malla'),
  (2, 'Yarbang'),
  (2, 'Abattoir'),
  (2, 'Aéroport'),
  (2, 'Aoudi'),
  (2, 'Choa'),
  (2, 'Lamidat'),
  (2, 'Mayo-Daneyel'),
  (2, 'Mbalang-Djalingo'),
  (2, 'Biskewal'),
  (2, 'Darang'),
  (2, 'Dara-Salam'),
  (2, 'Madem'),
  (2, 'Margueleng'),
  (2, 'Massola'),
  (2, 'Ngaouhora'),
  (2, 'Ngaoussay'),
  (2, 'Repyanga'),
  (2, 'Selbé-Darang'),
  (2, 'Véla-Mbaï'),
  (2, 'Yoko-Wouro'),
  (2, 'Youkou-Mayo-Dana'),
  (2, 'Mbaouré'),
  (2, 'Ndougueleng'),
  (2, 'Vogdjom'),
  (2, 'Bondjong'),
  (2, 'Ngaou-Tbala');

-- ── Ngaoundéré 3e ───────────────────────────────────────────────
INSERT INTO neighborhoods (city_id, name) VALUES
  (3, 'Bambi'),
  (3, 'Bini'),
  (3, 'Dang'),
  (3, 'Dang Ousmanou'),
  (3, 'Hore-Bini'),
  (3, 'Madjele'),
  (3, 'Malang'),
  (3, 'Malo-Goni'),
  (3, 'Malo-Mbifal'),
  (3, 'Manwi'),
  (3, 'Margol'),
  (3, 'Naboune'),
  (3, 'Gada-Bini'),
  (3, 'Gada-Bidou'),
  (3, 'Tchabal-Bambi'),
  (3, 'Tchabal-Mounguel'),
  (3, 'Tchabal-Baouro'),
  (3, 'Tchabal-Djalingo'),
  (3, 'Malang-Gare'),
  (3, 'Béka-Ngaoumoukone'),
  (3, 'Béka-Tinguereng'),
  (3, 'Ngaoumoukone'),
  (3, 'Ngodi'),
  (3, 'Ngodi-Mafal-Ngaou'),
  (3, 'Ngodi-Maïborno'),
  (3, 'Saltaka'),
  (3, 'Tellere'),
  (3, 'Tinguereng'),
  (3, 'Wouro-Soua'),
  (3, 'Roh');
